// ---------------------------------------------------------------------
//
// Copyright (c) 2020 - 2020 by the IBAMR developers
// All rights reserved.
//
// This file is part of IBAMR.
//
// IBAMR is free software and is distributed under the 3-clause BSD
// license. The full text of the license can be found in the file
// COPYRIGHT at the top level directory of IBAMR.
//
// ---------------------------------------------------------------------

#ifndef included_IBTK_MergingChopAndPackLoadBalancer
#define included_IBTK_MergingChopAndPackLoadBalancer

/////////////////////////////// INCLUDES /////////////////////////////////////

#include "ibtk/IBTK_MPI.h"
#include <ibtk/box_utilities.h>

#include "SAMRAI/tbox/PIO.h"


#include "SAMRAI/hier/Box.h"
#include "SAMRAI/hier/BoxContainer.h"
#include "SAMRAI/hier/BoxContainer.h"
#include "SAMRAI/mesh/ChopAndPackLoadBalancer.h"

#include <algorithm>
#include <set>
#include <utility>
#include <vector>

namespace SAMRAI
{
namespace hier
{
class ProcessorMapping;

class PatchHierarchy;
} // namespace hier
} // namespace SAMRAI

/////////////////////////////// CLASS DEFINITION /////////////////////////////

namespace IBTK
{
/*!
 * \brief Class MergingChopAndPackLoadBalancer merges the boxes generated by a load
 * balancer in a final step to decrease the total number of boxes. In essence,
 * it postprocesses the list of boxes generated by its parent class to try and
 * coalesce the set of boxes on each process.
 *
 * @note During regridding, the boxes generated by this class are subsequently
 * read by GriddingAlgorithm, which will enforce minimum and maximum size
 * constraints; i.e., to take full advantage of this class one must set up the
 * GriddingAlgorithm objects to have very large maximum box sizes.
 */
class MergingChopAndPackLoadBalancer : public SAMRAI::mesh::ChopAndPackLoadBalancer
{
public:
    // use parent constructor
    using SAMRAI::mesh::ChopAndPackLoadBalancer::ChopAndPackLoadBalancer;

    virtual void loadBalanceBoxes(SAMRAI::hier::BoxContainer& out_boxes,
                                  SAMRAI::hier::ProcessorMapping& mapping,
                                  const SAMRAI::hier::BoxList& in_boxes,
                                  const std::shared_ptr<SAMRAI::hier::PatchHierarchy > hierarchy,
                                  int level_number,
                                  const SAMRAI::hier::BoxContainer& physical_domain,
                                  const SAMRAI::hier::IntVector& ratio_to_hierarchy_level_zero,
                                  const SAMRAI::hier::IntVector& min_size,
                                  const SAMRAI::hier::IntVector& max_size,
                                  const SAMRAI::hier::IntVector& cut_factor,
                                  const SAMRAI::hier::IntVector& bad_interval) const override;
};
} // namespace IBTK

//////////////////////////////////////////////////////////////////////////////

#endif //#ifndef included_IBTK_MergingChopAndPackLoadBalancer
